using AmarTools.BuildingBlocks.Common;
using AmarTools.BuildingBlocks.Domain;

namespace AmarTools.Domain.Entities;

/// <summary>
/// Stores the admin-configured settings for the EventPhotoframeGenerator tool
/// within a specific event. One row per EventTool activation.
///
/// The <see cref="SharingSlug"/> is the public identifier used in the guest
/// landing page URL: <c>/photoframe/{slug}</c>.
/// </summary>
public sealed class PhotoFrameConfig : AuditableEntity
{
    // ── Ownership ─────────────────────────────────────────────────────────────

    /// <summary>FK to the EventTool row that activated this tool in the event.</summary>
    public Guid EventToolId { get; private set; }

    /// <summary>Navigation to the activating EventTool.</summary>
    public EventTool EventTool { get; private set; } = null!;

    // ── Frame Asset ───────────────────────────────────────────────────────────

    /// <summary>
    /// Storage-relative path to the uploaded frame PNG (e.g. <c>frames/abc123.png</c>).
    /// The frame is rendered on top of the guest photo — it should have
    /// transparent cut-out areas where the guest photo is visible.
    /// </summary>
    public string? FrameImagePath { get; private set; }

    /// <summary>Storage-relative path to the optional event logo image.</summary>
    public string? LogoImagePath { get; private set; }

    // ── Event Details (overlaid on the frame or shown on landing page) ────────

    public string  EventName    { get; private set; } = string.Empty;
    public string? SponsorName  { get; private set; }
    public string? VenueName    { get; private set; }
    public DateTime? EventDateTime { get; private set; }

    // ── Sharing ───────────────────────────────────────────────────────────────

    /// <summary>
    /// URL-safe slug used as the public identifier for the guest landing page.
    /// Auto-generated on creation; can be regenerated by the admin.
    /// Example: <c>techsummit-2025-a3f9</c>
    /// </summary>
    public string SharingSlug { get; private set; } = string.Empty;

    /// <summary>
    /// When <c>true</c>, the guest landing page is publicly accessible.
    /// Admins set this after finishing the frame setup.
    /// </summary>
    public bool IsPublished { get; private set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>Landing page design settings (one-to-one).</summary>
    public LandingPageConfig? LandingPage { get; private set; }

    // ── Factory ───────────────────────────────────────────────────────────────

    private PhotoFrameConfig() { }

    /// <summary>Creates a new (draft) photo frame configuration for an event tool.</summary>
    public static PhotoFrameConfig Create(Guid eventToolId, string eventName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(eventName);

        return new PhotoFrameConfig
        {
            EventToolId  = eventToolId,
            EventName    = eventName.Trim(),
            SharingSlug  = GenerateSlug(eventName),
            IsPublished  = false
        };
    }

    // ── Behaviour ─────────────────────────────────────────────────────────────

    /// <summary>Sets or replaces the uploaded frame PNG path.</summary>
    public void SetFrameImage(string storagePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(storagePath);
        FrameImagePath = storagePath;
    }

    /// <summary>Sets or replaces the event logo path.</summary>
    public void SetLogo(string? storagePath) => LogoImagePath = storagePath;

    /// <summary>Updates event detail metadata shown on the landing page.</summary>
    public void UpdateDetails(
        string eventName, string? sponsorName,
        string? venueName, DateTime? eventDateTime)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(eventName);
        EventName     = eventName.Trim();
        SponsorName   = sponsorName?.Trim();
        VenueName     = venueName?.Trim();
        // PostgreSQL timestamptz requires UTC — normalize Kind to avoid Npgsql exception
        EventDateTime = eventDateTime.HasValue
            ? DateTime.SpecifyKind(eventDateTime.Value, DateTimeKind.Utc)
            : null;
    }

    /// <summary>
    /// Publishes the landing page so guests can access it.
    /// Requires a frame image to be uploaded first.
    /// </summary>
    public Result Publish()
    {
        if (string.IsNullOrWhiteSpace(FrameImagePath))
            return Error.Failure("PhotoFrame.NoFrame",
                "Upload a frame image before publishing.");

        IsPublished = true;
        return Result.Ok;
    }

    /// <summary>Takes the landing page offline without deleting configuration.</summary>
    public void Unpublish() => IsPublished = false;

    /// <summary>Generates a new sharing slug (e.g. if the event is renamed).</summary>
    public void RegenerateSlug() => SharingSlug = GenerateSlug(EventName);

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string GenerateSlug(string eventName)
    {
        var slug = eventName
            .ToLowerInvariant()
            .Replace(' ', '-')
            .Where(c => char.IsLetterOrDigit(c) || c == '-')
            .Take(40)
            .ToArray();

        var suffix = Guid.NewGuid().ToString("N")[..4];
        return $"{new string(slug).Trim('-')}-{suffix}";
    }
}
